/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.generator;

import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;
import org.eclipse.xtext.xbase.lib.Exceptions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class LireCSV {
  public static ArrayList<ArrayList<String>> csvReader(final String filePath) {
    try {
      final ArrayList<ArrayList<String>> data = new ArrayList<ArrayList<String>>();
      final File fichier = new File(filePath);
      final Scanner scane = new Scanner(fichier);
      scane.useDelimiter(";");
      while (scane.hasNextLine()) {
        {
          final String line = scane.nextLine();
          final String[] values = line.split(";");
          ArrayList<String> row = new ArrayList<String>();
          for (final String v : values) {
            row.add(v);
          }
          data.add(row);
        }
      }
      scane.close();
      return data;
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
